api/urls.py
from django.urls import include, path

from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views

from api import views

router = routers.DefaultRouter()
router.register("games", views.GameViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("api/", include("account.urls")),
    path("api-auth-token", authtoken_views.obtain_auth_token, name="api-auth-token"),
    path("api-auth/", include("rest_framework.urls")),
]

core/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

urlpatterns = [
    path("", index, name="home"),
    path("<int:pk>", UserDetailView.as_view(), name="user-details"),
    path("new_game", GameCreateView.as_view(), name="game-create"),
    path("game/<int:pk>", game_detail, name="game"),
    path("<int:pk>/new_round", RoundCreateView.as_view(), name="round-create"),
]

dart_app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("api.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

from rest_framework import routers, serializers, viewsets


class Game(models.Model):
    MAX_SCORE_CHOICES = ((301, 301), (501, 501), (701, 701))
    BEST_OF_CHOICES = (
        (3, 3),
        (5, 5),
        (7, 7),
        (9, 9),
    )
    MODE_CHOICES = (
        ("single", "single out"),
        ("master", "master out"),
        ("double", "double out"),
    )
    users = models.ManyToManyField(User, related_name="games")
    finished = models.BooleanField(default=False)
    best_of = models.IntegerField(default=3)
    max_score = models.IntegerField(choices=MAX_SCORE_CHOICES)
    mode = models.CharField(choices=MODE_CHOICES, max_length=64)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        users = ", ".join([u.username for u in self.users.all()])
        return f"Game {self.id}"


class Set(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, default=None)


class Leg(models.Model):
    set = models.ForeignKey(Set, on_delete=models.CASCADE)
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, default=None)


class Round(models.Model):
    leg = models.ForeignKey(Leg, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

core/forms.py
from django import forms


class ScoreForm(forms.Form):
    score = forms.IntegerField(label="score", required=False)

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import DetailView
from django.views.generic.edit import CreateView

from .models import *
from .forms import *


def index(request):
    context = {"games": Game.objects.filter(users=request.user, finished=False)}

    return render(request, "core/index.html", context)


def game_update(request, pk):

    game = Game.objects.get(pk=pk)
    context = {"game": game}

    return render(request, "core/game_update.html", context)


def game_detail(request, pk):

    user_id = request.GET.get("player", None)
    if user_id is None:
        return game_update(request, pk)

    player = User.objects.get(username=user_id)
    game = Game.objects.get(pk=pk)

    form = ScoreForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        pass
        # Round.objects.create()

    context = {"game": game, "selected_player": player, "form": form}

    return render(request, "core/game_detail.html", context)


def login_create_view(request):
    context = {}

    return (request, "registration/login.html", context)


class UserDetailView(DetailView):
    model = User


class GameDetailView(DetailView):
    model = Game


class RoundCreateView(CreateView):
    model = Round
    fields = "__all__"
    template_name = "core/forms.html"


class GameCreateView(CreateView):
    model = Game
    fields = "__all__"
    template_name = "core/forms.html"
    success_url = reverse_lazy("round-create")

core/templates/core/base.html
<html>
	<header>
		<meta charset="UTF-8">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	</header>

<nav class="navbar navbar-dark bg-dark">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'home' %}">Ultimate Dart</a>
		{% if not request.user.is_authenticated %}
		<a href="{% url 'login' %}" class="btn btn-sm btn-primary">login</a>
		{% else %}
		<a href="{% url 'logout' %}" class="btn btn-sm btn-secondary">logout</a>
		{% endif%}
	</div>
</nav>

{% block content %}
<div class="container">
	<h1 class="text-center">Ultimate Dart APP</h1>
</div>
{% endblock %}
</html>

core/templates/core/forms.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-primary my-3">Submit</button>
	</form>
</div>
{% endblock %}

core/templates/core/game_detail.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	<h1 class="text-center">{{ game }}</h1>
	<div class="p-3 border rounded">
		{% include 'core/score_board.html' %}
	</div>
	<div class="row">
		<form method="POST">
			{% csrf_token %}
			<div class="input-group py-3">
			    <div class="input-group-text">score</div>
			    <input type="number" class="form-control" id="id_score"
				name="score" value="0">
			    <button type="submit" class="btn btn-primary input-group-text">validate</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

core/templates/core/game_update.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
	<h1 class="text-center">Select Player - {{ game }}</h1>
	<table class="table">
		<thead>
			<tr class="text-center">
				<td>place</td>
				<td>user</td>
			</tr>
		</thead>
		<tbody>
			{% for user in game.users.all %}
			<tr class="text-center">
				<td>{{ forloop.counter}}</td>
				<td>{{ user }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<a class="btn btn-primary" href="?player={{ game.users.first }}">Start</a>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
	<script src="{% static 'index.js' %}"></script>
{% endblock %}

{% block content %}
<div>
	<h1 class="text-center">Ultimate Dart APP</h1>
	<div class="row">
		<div class="col">
			<a class="btn btn-primary" href="{% url 'game-create' %}">Create Game</a>
		</div>
		<div class="col">History</div>
		<div class="col col-auto">
			<h2 class="text-center">Active Games</h2>
			<div class="toast-container p-3">
				{% for game in games %}
				<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
					<div class="toast-header">
						<strong class="me-auto">{{ game }} - Best of {{ game.best_of }}</strong>
						<small>{{ game.created_on }}</small>
						<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
				  </div>
				  <div class="toast-body">
					  
					  <span>{% include 'core/score_board.html' %}</span>
					<a href="{% url "game" game.id %}">join</a>
				  </div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/core/score_board.html
{% load core_extra %}
<table class="table">
	<thead>
		<tr class="text-center">
			<td>User</td>
			<td>Set</td>
			<td>Leg</td>
			<td>Score</td>
		</tr>
	</thead>
	<tbody>
		{% for player in game.users.all %}
		<tr class="text-center{% if player == selected_player %} table-warning{% endif %}">
			<td>{{ player }}</td>
			<td>{% nb_sets game player %}</td>
			<td>{% nb_legs game player %}</td>
			<td>{% score game player %}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>